version: '2'
services:
  web:
    image: ${IMAGE_NAME}
    ports:
      - "5000"
    networks:
      - ci
    labels:
      - "traefik.backend=petitions-data-driven"
      - "traefik.frontend.rule=Host:petitions-data-driven.ci.ukpds.org"
    environment:
      DATADRIVEN_ENDPOINT: data-driven.ci.ukpds.org
      SERVICE_CHECK_SCRIPT: curl --silent http://$$SERVICE_IP:$$SERVICE_PORT/healthcheck | grep Working

networks:
  ci:
    external: true