version: '2'
services:
  web:
    image: ${IMAGE_NAME}
    ports:
      - "5000"
    networks:
       - ci
    labels:
      - "traefik.backend=petitions-data-driven"
      - "traefik.frontend.rule=Host:petitions-data-driven.ci.ukpds.org"

networks:
  ci:
    external: true